[2025-07-03T14:51:28.959+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-03T14:51:28.976+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: connect_to_minio.explore_bucket_structure manual__2025-07-03T12:48:33.639150+00:00 [queued]>
[2025-07-03T14:51:28.980+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: connect_to_minio.explore_bucket_structure manual__2025-07-03T12:48:33.639150+00:00 [queued]>
[2025-07-03T14:51:28.981+0000] {taskinstance.py:2303} INFO - Starting attempt 12 of 12
[2025-07-03T14:51:28.987+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): explore_bucket_structure> on 2025-07-03 12:48:33.639150+00:00
[2025-07-03T14:51:28.992+0000] {standard_task_runner.py:63} INFO - Started process 403 to run task
[2025-07-03T14:51:28.994+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'connect_to_minio', 'explore_bucket_structure', 'manual__2025-07-03T12:48:33.639150+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/test_connection_to_minio.py', '--cfg-path', '/tmp/tmp_qt5jagv']
[2025-07-03T14:51:28.995+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask explore_bucket_structure
[2025-07-03T14:51:29.003+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-03T14:51:29.020+0000] {task_command.py:426} INFO - Running <TaskInstance: connect_to_minio.explore_bucket_structure manual__2025-07-03T12:48:33.639150+00:00 [running]> on host 1b628c5cb8e4
[2025-07-03T14:51:29.074+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='connect_to_minio' AIRFLOW_CTX_TASK_ID='explore_bucket_structure' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T12:48:33.639150+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-03T12:48:33.639150+00:00'
[2025-07-03T14:51:29.074+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-03T14:51:29.080+0000] {logging_mixin.py:188} INFO - ['accessKey']
[2025-07-03T14:51:29.081+0000] {logging_mixin.py:188} INFO - ['secretKey']
[2025-07-03T14:51:29.133+0000] {logging_mixin.py:188} INFO - 
 TOP-LEVEL DIRECTORIES:
[2025-07-03T14:51:29.135+0000] {logging_mixin.py:188} INFO - Error exploring bucket: sequence item 0: expected str instance, list found
[2025-07-03T14:51:29.135+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-03T14:51:29.135+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_connection_to_minio.py", line 43, in explore_bucket_structure
    response = s3_client.list_objects_v2(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 195, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/auth.py", line 432, in add_auth
    self._inject_signature_to_request(request, signature)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/auth.py", line 435, in _inject_signature_to_request
    auth_str = ['AWS4-HMAC-SHA256 Credential=%s' % self.scope(request)]
                                                   ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/auth.py", line 384, in scope
    return '/'.join(scope)
           ^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, list found
[2025-07-03T14:51:29.143+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=connect_to_minio, task_id=explore_bucket_structure, execution_date=20250703T124833, start_date=20250703T145128, end_date=20250703T145129
[2025-07-03T14:51:29.151+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task explore_bucket_structure (sequence item 0: expected str instance, list found; 403)
[2025-07-03T14:51:29.165+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-03T14:51:29.180+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-03T14:51:29.183+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
