[2025-07-06T05:27:58.065+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T05:27:58.082+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_spark_inline.spark_write_data manual__2025-07-06T05:12:58.943989+00:00 [queued]>
[2025-07-06T05:27:58.086+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_spark_inline.spark_write_data manual__2025-07-06T05:12:58.943989+00:00 [queued]>
[2025-07-06T05:27:58.086+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 5
[2025-07-06T05:27:58.092+0000] {taskinstance.py:2327} INFO - Executing <Task(SparkSubmitOperator): spark_write_data> on 2025-07-06 05:12:58.943989+00:00
[2025-07-06T05:27:58.096+0000] {standard_task_runner.py:63} INFO - Started process 1289 to run task
[2025-07-06T05:27:58.142+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_spark_inline', 'spark_write_data', 'manual__2025-07-06T05:12:58.943989+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmprh9m9xuh']
[2025-07-06T05:27:58.144+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask spark_write_data
[2025-07-06T05:27:58.156+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T05:27:58.177+0000] {task_command.py:426} INFO - Running <TaskInstance: my_spark_inline.spark_write_data manual__2025-07-06T05:12:58.943989+00:00 [running]> on host 1d0c55f2b911
[2025-07-06T05:27:58.280+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_spark_inline' AIRFLOW_CTX_TASK_ID='spark_write_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T05:12:58.943989+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T05:12:58.943989+00:00'
[2025-07-06T05:27:58.280+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T05:27:58.298+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-07-06T05:27:58.338+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master local[*] --conf spark.master=local[*] --name arrow-spark --queue root.default --deploy-mode client /opt/spark_project/src/spark/spark_main.py
[2025-07-06T05:27:58.840+0000] {spark_submit.py:634} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-07-06T05:28:01.398+0000] {spark_submit.py:634} INFO - python3: can't open file '/opt/spark_project/src/spark/spark_main.py': [Errno 2] No such file or directory
[2025-07-06T05:28:01.412+0000] {spark_submit.py:634} INFO - 25/07/06 05:28:01 INFO ShutdownHookManager: Shutdown hook called
[2025-07-06T05:28:01.441+0000] {spark_submit.py:634} INFO - 25/07/06 05:28:01 INFO ShutdownHookManager: Deleting directory /tmp/spark-9648e34d-860a-4e13-bfb5-5ca94f682e34
[2025-07-06T05:28:01.476+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T05:28:01.483+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local[*] --conf spark.master=local[*] --name arrow-spark --queue root.default --deploy-mode client /opt/spark_project/src/spark/spark_main.py. Error code is: 2.
[2025-07-06T05:28:01.485+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=my_spark_inline, task_id=spark_write_data, execution_date=20250706T051258, start_date=20250706T052758, end_date=20250706T052801
[2025-07-06T05:28:01.492+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task spark_write_data (Cannot execute: spark-submit --master local[*] --conf spark.master=local[*] --name arrow-spark --queue root.default --deploy-mode client /opt/spark_project/src/spark/spark_main.py. Error code is: 2.; 1289)
[2025-07-06T05:28:01.521+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-06T05:28:01.533+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T05:28:01.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
