[2025-07-06T12:29:57.866+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T12:29:57.886+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_spark_inline.spark_write_data manual__2025-07-06T05:12:58.943989+00:00 [queued]>
[2025-07-06T12:29:58.026+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_spark_inline.spark_write_data manual__2025-07-06T05:12:58.943989+00:00 [queued]>
[2025-07-06T12:29:58.026+0000] {taskinstance.py:2303} INFO - Starting attempt 30 of 30
[2025-07-06T12:29:58.043+0000] {taskinstance.py:2327} INFO - Executing <Task(SparkSubmitOperator): spark_write_data> on 2025-07-06 05:12:58.943989+00:00
[2025-07-06T12:29:58.050+0000] {standard_task_runner.py:63} INFO - Started process 2947 to run task
[2025-07-06T12:29:58.052+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_spark_inline', 'spark_write_data', 'manual__2025-07-06T05:12:58.943989+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmp0lmwl482']
[2025-07-06T12:29:58.054+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask spark_write_data
[2025-07-06T12:29:58.064+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T12:29:58.089+0000] {task_command.py:426} INFO - Running <TaskInstance: my_spark_inline.spark_write_data manual__2025-07-06T05:12:58.943989+00:00 [running]> on host 320a39989f12
[2025-07-06T12:29:58.142+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_spark_inline' AIRFLOW_CTX_TASK_ID='spark_write_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T05:12:58.943989+00:00' AIRFLOW_CTX_TRY_NUMBER='30' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T05:12:58.943989+00:00'
[2025-07-06T12:29:58.142+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T12:29:58.155+0000] {base.py:84} INFO - Using connection ID 'spark-master' for task execution.
[2025-07-06T12:29:58.156+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark-master:7077 --packages com.clickhouse:clickhouse-jdbc:0.6.4,org.apache.httpcomponents.client5:httpclient5:5.3.1,org.apache.hadoop:hadoop-aws-3.3.4,com.amazonaws:aws-java-sdk-bundle-1.12.761 --name arrow-spark --deploy-mode client /opt/***/spark_project/src/spark/spark_main_minio.py
[2025-07-06T12:29:58.399+0000] {spark_submit.py:634} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-07-06T12:30:00.041+0000] {spark_submit.py:634} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.3.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-07-06T12:30:00.140+0000] {spark_submit.py:634} INFO - Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Provided Maven Coordinates must be in the form 'groupId:artifactId:version'. The coordinate provided is: org.apache.hadoop:hadoop-aws-3.3.4
[2025-07-06T12:30:00.141+0000] {spark_submit.py:634} INFO - at scala.Predef$.require(Predef.scala:337)
[2025-07-06T12:30:00.141+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.MavenUtils$.$anonfun$extractMavenCoordinates$1(MavenUtils.scala:102)
[2025-07-06T12:30:00.141+0000] {spark_submit.py:634} INFO - at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:936)
[2025-07-06T12:30:00.141+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.MavenUtils$.extractMavenCoordinates(MavenUtils.scala:98)
[2025-07-06T12:30:00.142+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.MavenUtils$.resolveMavenCoordinates(MavenUtils.scala:472)
[2025-07-06T12:30:00.142+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:123)
[2025-07-06T12:30:00.142+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:341)
[2025-07-06T12:30:00.142+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:961)
[2025-07-06T12:30:00.142+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:204)
[2025-07-06T12:30:00.142+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:227)
[2025-07-06T12:30:00.142+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:96)
[2025-07-06T12:30:00.142+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1132)
[2025-07-06T12:30:00.143+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1141)
[2025-07-06T12:30:00.143+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-07-06T12:30:00.167+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T12:30:00.227+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --packages com.clickhouse:clickhouse-jdbc:0.6.4,org.apache.httpcomponents.client5:httpclient5:5.3.1,org.apache.hadoop:hadoop-aws-3.3.4,com.amazonaws:aws-java-sdk-bundle-1.12.761 --name arrow-spark --deploy-mode client /opt/***/spark_project/src/spark/spark_main_minio.py. Error code is: 1.
[2025-07-06T12:30:00.231+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=my_spark_inline, task_id=spark_write_data, execution_date=20250706T051258, start_date=20250706T122957, end_date=20250706T123000
[2025-07-06T12:30:00.239+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task spark_write_data (Cannot execute: spark-submit --master spark-master:7077 --packages com.clickhouse:clickhouse-jdbc:0.6.4,org.apache.httpcomponents.client5:httpclient5:5.3.1,org.apache.hadoop:hadoop-aws-3.3.4,com.amazonaws:aws-java-sdk-bundle-1.12.761 --name arrow-spark --deploy-mode client /opt/***/spark_project/src/spark/spark_main_minio.py. Error code is: 1.; 2947)
[2025-07-06T12:30:00.269+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-06T12:30:00.281+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T12:30:00.281+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
