[2025-07-04T01:54:03.138+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T01:54:03.154+0000] {taskinstance.py:2063} INFO - Dependencies not met for <TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'explore_ga4_data'}
[2025-07-04T01:54:03.155+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
[2025-07-04T01:54:50.183+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T01:54:50.203+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T01:54:50.207+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T01:54:50.207+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-04T01:54:50.213+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): download_one_file> on 2025-07-03 00:00:00+00:00
[2025-07-04T01:54:50.218+0000] {standard_task_runner.py:63} INFO - Started process 1022 to run task
[2025-07-04T01:54:50.220+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'connect_to_minio', 'download_one_file', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/test_connection_to_minio.py', '--cfg-path', '/tmp/tmp_wblzh89']
[2025-07-04T01:54:50.222+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask download_one_file
[2025-07-04T01:54:50.230+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T01:54:50.251+0000] {task_command.py:426} INFO - Running <TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [running]> on host 0f95c2c3c3d6
[2025-07-04T01:54:50.298+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='connect_to_minio' AIRFLOW_CTX_TASK_ID='download_one_file' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T01:54:50.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T01:54:50.352+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T01:54:50.352+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_connection_to_minio.py", line 134, in download_one_file
    client.fget_object(bucket_name, obj_key, local_path)
    ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 906, in __getattr__
    raise AttributeError(
AttributeError: 'S3' object has no attribute 'fget_object'
[2025-07-04T01:54:50.359+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=connect_to_minio, task_id=download_one_file, execution_date=20250703T000000, start_date=20250704T015450, end_date=20250704T015450
[2025-07-04T01:54:50.365+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task download_one_file ('S3' object has no attribute 'fget_object'; 1022)
[2025-07-04T01:54:50.391+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T01:54:50.401+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T01:54:50.402+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-04T07:45:12.560+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T07:45:12.582+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T07:45:12.586+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T07:45:12.586+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-04T07:45:12.592+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): download_one_file> on 2025-07-03 00:00:00+00:00
[2025-07-04T07:45:12.596+0000] {standard_task_runner.py:63} INFO - Started process 2437 to run task
[2025-07-04T07:45:12.598+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'connect_to_minio', 'download_one_file', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test_connection_to_minio.py', '--cfg-path', '/tmp/tmpshgv4hbp']
[2025-07-04T07:45:12.599+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask download_one_file
[2025-07-04T07:45:12.607+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T07:45:12.626+0000] {task_command.py:426} INFO - Running <TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [running]> on host dd53cfd6a5de
[2025-07-04T07:45:12.672+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='connect_to_minio' AIRFLOW_CTX_TASK_ID='download_one_file' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T07:45:12.672+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T07:45:13.136+0000] {logging_mixin.py:188} INFO - ✅ Đã tải file về: /opt/***/data/data_example.parquet
[2025-07-04T07:45:13.137+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-04T07:45:13.138+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T07:45:13.148+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=connect_to_minio, task_id=download_one_file, execution_date=20250703T000000, start_date=20250704T074512, end_date=20250704T074513
[2025-07-04T07:45:13.210+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-04T07:45:13.227+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T07:45:13.228+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
