[2025-07-08T09:39:25.563+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-08T09:39:25.578+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-08T09:39:19.707078+00:00 [queued]>
[2025-07-08T09:39:25.581+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-08T09:39:19.707078+00:00 [queued]>
[2025-07-08T09:39:25.582+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-08T09:39:25.587+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): no_new_data_message> on 2025-07-08 09:39:19.707078+00:00
[2025-07-08T09:39:25.591+0000] {standard_task_runner.py:63} INFO - Started process 8223 to run task
[2025-07-08T09:39:25.626+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_ga4_new_file_detector', 'no_new_data_message', 'manual__2025-07-08T09:39:19.707078+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/dag_automatic.py', '--cfg-path', '/tmp/tmp7h6ymuyq']
[2025-07-08T09:39:25.628+0000] {standard_task_runner.py:91} INFO - Job 178: Subtask no_new_data_message
[2025-07-08T09:39:25.639+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-08T09:39:25.656+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-08T09:39:19.707078+00:00 [running]> on host 1a66de7e9daf
[2025-07-08T09:39:25.732+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_ga4_new_file_detector' AIRFLOW_CTX_TASK_ID='no_new_data_message' AIRFLOW_CTX_EXECUTION_DATE='2025-07-08T09:39:19.707078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-08T09:39:19.707078+00:00'
[2025-07-08T09:39:25.733+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-08T09:39:25.742+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-08T09:39:25.743+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Không có dữ liệu GA4 mới để xử lý trong lần chạy này."']
[2025-07-08T09:39:25.756+0000] {subprocess.py:86} INFO - Output:
[2025-07-08T09:39:25.758+0000] {subprocess.py:93} INFO - Không có dữ liệu GA4 mới để xử lý trong lần chạy này.
[2025-07-08T09:39:25.758+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-08T09:39:25.758+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-08T09:39:25.777+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=minio_ga4_new_file_detector, task_id=no_new_data_message, execution_date=20250708T093919, start_date=20250708T093925, end_date=20250708T093925
[2025-07-08T09:39:25.805+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-08T09:39:25.835+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-08T09:39:25.836+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
