[2025-07-07T07:25:57.285+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T07:25:57.301+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:25:57.306+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:25:57.306+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2025-07-07T07:25:57.311+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): no_new_data_message> on 2025-07-07 06:53:38.076557+00:00
[2025-07-07T07:25:57.314+0000] {standard_task_runner.py:63} INFO - Started process 4423 to run task
[2025-07-07T07:25:57.318+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_ga4_new_file_detector', 'no_new_data_message', 'manual__2025-07-07T06:53:38.076557+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/dag_automatic.py', '--cfg-path', '/tmp/tmp4s_8sbqm']
[2025-07-07T07:25:57.319+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask no_new_data_message
[2025-07-07T07:25:57.334+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T07:25:57.359+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-07T06:53:38.076557+00:00 [running]> on host 34b334fe6b50
[2025-07-07T07:25:57.407+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_ga4_new_file_detector' AIRFLOW_CTX_TASK_ID='no_new_data_message' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:53:38.076557+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:53:38.076557+00:00'
[2025-07-07T07:25:57.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T07:25:57.413+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T07:25:57.413+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Không có dữ liệu GA4 mới để xử lý trong lần chạy này."']
[2025-07-07T07:25:57.422+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T07:25:57.423+0000] {subprocess.py:93} INFO - Không có dữ liệu GA4 mới để xử lý trong lần chạy này.
[2025-07-07T07:25:57.423+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-07T07:25:57.423+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T07:25:57.444+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=minio_ga4_new_file_detector, task_id=no_new_data_message, execution_date=20250707T065338, start_date=20250707T072557, end_date=20250707T072557
[2025-07-07T07:25:57.488+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-07T07:25:57.499+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T07:25:57.500+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
