[2025-07-07T07:16:47.387+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T07:16:47.408+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:16:47.413+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:16:47.413+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-07T07:16:47.418+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): no_new_data_message> on 2025-07-07 06:53:38.076557+00:00
[2025-07-07T07:16:47.423+0000] {standard_task_runner.py:63} INFO - Started process 3688 to run task
[2025-07-07T07:16:47.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_ga4_new_file_detector', 'no_new_data_message', 'manual__2025-07-07T06:53:38.076557+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/dag_automatic.py', '--cfg-path', '/tmp/tmps_lkqqeo']
[2025-07-07T07:16:47.426+0000] {standard_task_runner.py:91} INFO - Job 149: Subtask no_new_data_message
[2025-07-07T07:16:47.433+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T07:16:47.453+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_ga4_new_file_detector.no_new_data_message manual__2025-07-07T06:53:38.076557+00:00 [running]> on host 34b334fe6b50
[2025-07-07T07:16:47.498+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_ga4_new_file_detector' AIRFLOW_CTX_TASK_ID='no_new_data_message' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:53:38.076557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:53:38.076557+00:00'
[2025-07-07T07:16:47.499+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T07:16:47.504+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T07:16:47.505+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Không có dữ liệu GA4 mới để xử lý trong lần chạy này."']
[2025-07-07T07:16:47.514+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T07:16:47.515+0000] {subprocess.py:93} INFO - Không có dữ liệu GA4 mới để xử lý trong lần chạy này.
[2025-07-07T07:16:47.515+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-07T07:16:47.515+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T07:16:47.534+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=minio_ga4_new_file_detector, task_id=no_new_data_message, execution_date=20250707T065338, start_date=20250707T071647, end_date=20250707T071647
[2025-07-07T07:16:47.556+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-07T07:16:47.568+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T07:16:47.568+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
